version: 2
updates:

- package-ecosystem: "pip"
  directory: "signer/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "pip"
  directory: "repo/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/create-signing-events/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/online-sign/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/signing-event/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/upload-repository/"
  schedule:
    interval: "daily"
    time: "10:25"
