name: 'Upload Repository artifacts'
description: 'Build a publishable repository version and upload it as GitHub artifacts'

inputs:
  gh_pages:
    description: 'Upload a GitHub Pages compatible single artifact'
    required: false
    default: false
  metadata_path:
    description: 'Relative published metadata path (only useful with gh_pages)'
    required: false
    default: "metadata"
  artifacts_path:
    description: 'relative published artifact path (only useful with gh_pages)'
    required: false
    default: "metadata"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: "3.11"

    - run: pip install $GITHUB_ACTION_PATH/../../repo/
      shell: bash

    - id: Build repository
      run: |
        mkdir build
        tuf-on-ci-build-repository --metadata build/${{inputs.metadata_path}}  --artifacts build/build/${{inputs.artifacts_path}}

        find build -type f | xargs ls -lh
      shell: bash

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      if: inputs.gh_pages == false
      with:
        name: metadata
        path: build/${{inputs.metadata_path}}/*

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      if: inputs.gh_pages == false
      with:
        name: artifacts
        path: build/${{inputs.artifacts_path}}/*

    - uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
      if: inputs.gh_pages == true
      with:
        path: build/*
