name: Lint actions & workflows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint-actions-and-workflows:
    permissions:
      security-events: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: |
          actions/lint-requirements.txt

    - name: Install zizmor
      run: python -m pip install -r actions/lint-requirements.txt

    - name: Run zizmor
      run: zizmor --pedantic .
