name: Lint & test

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        toxenv: [lint-signer, test-signer]
        pyversion: ['3.9', '3.12']
        os: [ubuntu-latest, macos-latest]
        # Only run repository on 3.12 (dependency pinning is easier with single version)
        include:
          - toxenv: lint-repo
            pyversion: '3.12'
            os: ubuntu-latest
          - toxenv: test-repo
            pyversion: '3.12'
            os: ubuntu-latest
          - toxenv: test-e2e
            pyversion: '3.12'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ matrix.pyversion }}
        cache: 'pip'
        cache-dependency-path: |
          signer/pyproject.toml
          repo/pyproject.toml
          action-constraints.txt
          build/build-constraints.txt

    - name: Install system dependencies for e2e test
      if: matrix.toxenv == 'test-e2e'
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: Install tox
      run: python -m pip install -c build/build-constraints.txt tox

    - name: ${{ matrix.toxenv }}
      run: tox
